apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wescale

images:
  - name: apecloud/wesql-server
    newTag: 8.0.35-6.alpha10.20240918.g18ad68b.25
  - name: apecloud/apecloud-mysql-scale
    newTag: 0.3.3
