apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wescale

images:
  - name: apecloud/wesql-server
    newTag: 8.0.35-0.1.0_beta2.37
  - name: apecloud/apecloud-mysql-scale
    newTag: 0.3.7
