apiVersion: v1
kind: Service
metadata:
  name: wesql-monitoring-public-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
