apiVersion: v1
kind: Service
metadata:
  name: mycluster-wesql-public-service
  namespace: default
  labels:
    app.kubernetes.io/component: wesql
    app.kubernetes.io/instance: mycluster
spec:
  type: LoadBalancer
  ports:
    - name: wesql
      port: 3306
      protocol: TCP
      targetPort: wesql
  selector:
    app.kubernetes.io/component: wesql
    app.kubernetes.io/instance: mycluster