{
 "title": "performance overview (auto-generated)",
 "description": "performance overview in development environment",
 "tags": [
  "vitess-mixin",
  "devview",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "host",
    "label": "Host(s)",
    "query": "label_values(vttablet_build_number{}, instance)"
   },
   {
    "name": "vtgate_host",
    "label": "Host(s)",
    "query": "label_values(vtgate_build_number, instance)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "query_result(sum by(table)(vitess_mixin:vtgate_queries_processed_by_table:rate1m{keyspace=\"$keyspace\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  vitess_mixin:vtgate_api_count:rate1m\n)\n"
    }
   ]
  },
  {
   "title": "Query success - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 \n-\nsum(\n  rate(\n    vtgate_api_error_counts{\n      job=\"vitess-vtgate\"\n    }[$interval]\n  ) OR vector(0)\n)\n/\nsum(\n  rate(\n    vtgate_api_count{\n      job=\"vitess-vtgate\"\n    }[$interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Query latency p99",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\n  0.99,\n  sum by(le)(\n    vitess_mixin:vtgate_api_bucket:rate1m\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Read Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(vttablet_queries_count{plan_type=~\"Select|SelectImpossible|OtherRead|Show\"})\n    /\nsum(vttablet_queries_count{plan_type=~\"Select|SelectImpossible|OtherRead|Show|Insert|Update|Delete\"}) * 100, 0.1)\n"
    }
   ]
  },
  {
   "title": "Write Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(vttablet_queries_count{plan_type=~\"Insert|Update|Delete\"})\n    /\nsum(vttablet_queries_count{plan_type=~\"Select|SelectImpossible|OtherRead|Show|Insert|Update|Delete\"}) * 100, 0.1)\n"
    }
   ]
  },
  {
   "title": "Connections In Use - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  vitess_mixin:vttablet_connections_in_use:rate1m\n)\n"
    }
   ]
  },
  {
   "title": "Connections Established - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  vitess_mixin:vttablet_connections_active:rate1m\n)\n"
    }
   ]
  },
  {
   "title": "Requests (VTGate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vtgate_api_count{\n      instance=~'$vtgate_host'\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests (by tablet_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (db_type)(\n  vitess_mixin:vtgate_api_count_by_db_type:rate1m\n)\n",
     "legendFormat": "{{db_type}}"
    }
   ]
  },
  {
   "title": "Requests (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by(keyspace)(\n  vitess_mixin:vtgate_api_count_by_keyspace:rate1m\n)\n",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Requests (VTTablet)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum  by (instance)(\n  rate(\n    vttablet_query_counts{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests (by plan type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, plan_type)(\n  rate(\n    vttablet_queries_count{\n      instance=~\"$host\"\n    } [1m]\n  )\n)\n",
     "legendFormat": "{{instance}} | {{plan_type}}"
    }
   ]
  },
  {
   "title": "Requests (by table)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (table)(\n  vitess_mixin:vttablet_query_counts_by_keyspace_table:rate1m{\n    table=~\"$table\"\n  }\n)\nor\nvector(0)\n",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Duration (Avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n    vtgate_api_sum[5m]\n  )\n)\n/\nsum (\n  rate(\n    vtgate_api_count[5m]\n    )\n  )\n",
     "legendFormat": "Avg Latency (vtgate)"
    },
    {
     "expr": "sum (\n  rate(\n    vttablet_queries_sum[5m]\n  )\n)\n/\nsum (\n  rate(\n    vttablet_queries_count[5m]\n    )\n  )\n",
     "legendFormat": "Avg Latency (vttablet)"
    },
    {
     "expr": "sum (\n  rate(\n    vttablet_mysql_sum[5m]\n  )\n)\n/\nsum (\n  rate(\n    vttablet_mysql_count[5m]\n    )\n  )\n",
     "legendFormat": "Avg Latency (mysql)"
    }
   ]
  },
  {
   "title": "Duration 50th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by(le)(\n    vitess_mixin:vtgate_api_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p50 (vtgate)"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by(le)(\n    vitess_mixin:vttablet_queries_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p50 (vttablet)"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by(le)(\n    vitess_mixin:vttablet_mysql_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p50 (mysql)"
    }
   ]
  },
  {
   "title": "Duration 95th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le)(\n    vitess_mixin:vtgate_api_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p95 (vtgate)"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le)(\n    vitess_mixin:vttablet_queries_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p95 (vttablet)"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le)(\n    vitess_mixin:vttablet_mysql_bucket:rate1m\n  )\n)\n",
     "legendFormat": "Duration p95 (mysql)"
    }
   ]
  },
  {
   "title": "Duration (VTTablet Transaction)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Transaction Duration (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(\n  rate(\n    vttablet_transactions_sum{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n/\nsum by(instance)(\n  rate(\n    vttablet_transactions_count{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Duration (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,sum by(instance,le)(\n    rate(\n      vttablet_transactions_bucket{\n        instance=~\"$host\"\n      }[1m]\n    )\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Duration (p95)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,sum by(instance,le)(\n    rate(\n      vttablet_transactions_bucket{\n        instance=~\"$host\"\n      }[1m]\n    )\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors (VTGate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "Errors (by code)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(\n  vitess_mixin:vtgate_api_error_counts_by_code:rate1m\n)\n",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors (by operation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(\n  vitess_mixin:vtgate_api_error_counts_by_operation:rate1m\n)\n",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors (by tablet_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (db_type)(\n  vitess_mixin:vtgate_api_error_counts_by_db_type:rate1m\n)\n",
     "legendFormat": "{{db_type}}"
    }
   ]
  },
  {
   "title": "WeScale - Query pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true
  },
  {
   "title": "Available Connections",
   "type": "graph",
   "description": "number of available connections in the pool in real-time",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  vttablet_conn_pool_available{\n    instance=~'$host'\n  }\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "count of in use connections to mysql",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  vttablet_conn_pool_active{\n    instance=~'$host'\n  }\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle Closed Rate",
   "type": "graph",
   "description": "rate of closing connections due to the idle timeout",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vttablet_conn_pool_idle_closed{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wait count",
   "type": "graph",
   "description": "WaitCount will give you how often the transaction pool gets full that causes new transactions to wait.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vttablet_conn_pool_wait_count{\n      instance=~'$host'\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg wait time",
   "type": "graph",
   "description": "WaitTime/WaitCount will tell you the average wait time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(\n    vttablet_conn_pool_wait_time{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n/\nsum by (instance) (\n  rate(\n    vttablet_conn_pool_wait_count{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WeScale - Transaction pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true
  },
  {
   "title": "Available Connections",
   "type": "graph",
   "description": "number of available connections in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  vttablet_transaction_pool_available{\n    instance=~'$host'\n  }\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of connections actually open to mysql",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (\n  vttablet_transaction_pool_active{\n    instance=~'$host'\n  }\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle Closed Rate",
   "type": "graph",
   "description": "Rate of closing connections due to the idle timeout",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vttablet_transaction_pool_idle_closed{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wait count",
   "type": "graph",
   "description": "WaitCount will give you how often the transaction pool gets full that causes new transactions to wait.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vttablet_transaction_pool_wait_count{\n      instance=~'$host'\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg wait time",
   "type": "graph",
   "description": "WaitTime/WaitCount will tell you the average wait time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(\n    vttablet_transaction_pool_wait_time{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n/\nsum by (instance) (\n  rate(\n    vttablet_transaction_pool_wait_count{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active connections of All Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true
  },
  {
   "title": "Active Connections of All Pools",
   "type": "graph",
   "description": "Number of active connections in all connection pools",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, __name__) (\n  {__name__=~\"vttablet.*active\", instance=~\"$host\"}\n)\n",
     "legendFormat": "{{instance}} - {{__name__}}"
    }
   ]
  },
  {
   "title": "WeScale Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true
  },
  {
   "title": "VtGate -> VtTablet Call Time (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(\n  rate(\n    vtgate_vttablet_call_sum[1m]\n  )\n)\n/\nsum by (instance)(\n  rate(\n    vtgate_vttablet_call_count[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Time Distribution (Heatmap)",
   "type": "heatmap",
   "description": "Shows a heatmap of the histogram bucketing of the time per read query.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 84 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    vttablet_queries_bucket{\n      instance=~\"$host\"\n      }[1m]\n    )\n  )\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rows returned",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true
  },
  {
   "title": "Rows Returned (by table)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,table) (\n  rate(\n    vttablet_query_rows_returned{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}} | {{table}}"
    }
   ]
  },
  {
   "title": "Rows Returned (by plan)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,plan) (\n  rate(\n    vttablet_query_rows_returned{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}} | {{plan}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true
  },
  {
   "title": "GC Count (vttablet)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(\n  rate(\n    go_gc_duration_seconds_count{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration total per second (vttablet)",
   "type": "graph",
   "description": "A summary of the pause duration of garbage collection cycles",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(\n  rate(\n    go_gc_duration_seconds_count{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration quantiles (vttablet - all hosts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(quantile)(\n  rate(\n    go_gc_duration_seconds{\n      instance=~\"$host\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "p{{quantile}}"
    }
   ]
  },
  {
   "title": "GC Count (vtgate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(\n  rate(\n    go_gc_duration_seconds_count{\n      job=\"vitess-vtgate\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration total per second (vtgate)",
   "type": "graph",
   "description": "A summary of the pause duration of garbage collection cycles",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(\n  rate(\n    go_gc_duration_seconds_count{\n      job=\"vitess-vtgate\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration quantiles (vtgate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(quantile)(\n  rate(\n    go_gc_duration_seconds{\n      job=\"vitess-vtgate\"\n    }[1m]\n  )\n)\n",
     "legendFormat": "p{{quantile}}"
    }
   ]
  }
 ]
}