apiVersion: v1
kind: ConfigMap
metadata:
  name: wesql-server-config
data:
  MYSQL_CUSTOM_CONFIG: |
    [mysqld]
    serverless=on
    objectstore_provider=aws
    objectstore_region=us-east-1
    objectstore_bucket=wesql-cluster-test
    datadir=/data/mysql/data
    log-error=/data/mysql/log/mysqld-error.log
    log-bin=binlog