apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wescale

images:
  - name: apecloud/wesql-server
    newTag: 8.0.35-6.alpha10.20240918.g18ad68b.25
  - name: apecloud/apecloud-mysql-scale
    newTag: 0.3.0-alpha26

patches:
  - target:
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/storageclass=standard"
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: mycluster-wesql-0
      spec:
        template:
          spec:
            containers:
              - name: mysql
                resources:
                  limits:
                    cpu: "0"
                    memory: "0"
                  requests:
                    cpu: "0"
                    memory: "0"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 500Mi
              storageClassName: local-path
  - target:
      kind: PersistentVolumeClaim
      name: etcd-data-pvc
    patch: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: etcd-data-pvc
      spec:
        storageClassName: local-path