apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wescale

images:
  - name: apecloud/wesql-server
    newTag: ${WESQL_SERVER_TAG}
  - name: apecloud/apecloud-mysql-scale
    newTag: ${WESCALE_TAG}

patches:
  - target:
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/storageclass=standard"
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: mycluster-wesql-0
      spec:
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: standard
  - target:
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/name=wesql-vtcontroller"
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wesql-vtcontroller
      spec:
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 100Mi
              storageClassName: standard