apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wescale

images:
  - name: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/wesql-server
    newTag: 8.0.35-6.alpha10.20240918.g18ad68b.25
  - name: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale
    newTag: autoscale-demo-12

patches:
  - target:
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/storageclass=standard"
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: mycluster-wesql-0
      spec:
        volumeClaimTemplates:
          - spec:
              storageClassName: gp2