apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wesql-server
  - wesql-server-config.yaml
  - wesql-server-secret.yaml

images:
    - name: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/wesql-server
      newTag: 8.0.35-6.alpha10.20240918.g18ad68b.25
