apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wesql-server

images:
  - name: apecloud/wesql-server
    newTag: 8.0.35-0.1.0_beta2.37


patches:
  - target:
      kind: StatefulSet
      labelSelector: "app.kubernetes.io/storageclass=standard"
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: mycluster-wesql-0
      spec:
        template:
          spec:
            containers:
              - name: mysql
                resources:
                  limits:
                    cpu: "0"
                    memory: "0"
                  requests:
                    cpu: "0"
                    memory: "0"
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 500Mi
              storageClassName: local-path