apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wesql-server
  - wescale-config.yaml
  - wescale-scripts.yaml
  - wescale-vtcontroller.yaml
  - wescale-vtcontroller-svc.yaml
  - wescale-rbac.yaml
  - wescale-vtgate.yaml

images:
    - name: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/wesql-server
      newTag: 8.0.35-6.alpha10.20240918.g18ad68b.25
    - name: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale
      newTag: autoscale-demo-12

patches:
  - target:
      kind: StatefulSet
      name: mycluster-wesql-0
    path: add-vttablet-container.yaml
  - target:
      kind: StatefulSet
      name: mycluster-wesql-0
    path: add-vttablet-volumes.yaml