apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../wesql-server
  - wescale-config.yaml
  - wescale-scripts.yaml
  - wescale-vtcontroller.yaml
  - wescale-vtcontroller-svc.yaml
  - wescale-rbac.yaml
  - wescale-vtgate.yaml
  - wescale-vtgate-svc.yaml

patches:
  - target:
      kind: StatefulSet
      name: mycluster-wesql-0
    path: add-vttablet-container.yaml
  - target:
      kind: StatefulSet
      name: mycluster-wesql-0
    path: add-vttablet-volumes.yaml