apiVersion: apps/v1
kind: Deployment
metadata:
  name: wesql-vtgate
  namespace: default
  labels:
    app.kubernetes.io/name: wesql-vtgate
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wesql-vtgate
  template:
    metadata:
      annotations:
        apps.kubeblocks.io/component-replicas: "1"
      labels:
        app.kubernetes.io/name: wesql-vtgate
    spec:
      serviceAccountName: wesql-autoscale-sa
      containers:
        - name: vtgate
          image: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale:0.3.0-alpha15
          imagePullPolicy: IfNotPresent
          command:
            - /scripts/vtgate.sh
          env:
            - name: VTGATE_WEB_PORT
              value: "15001"
            - name: VTGATE_GRPC_PORT
              value: "15991"
            - name: VTGATE_MYSQL_PORT
              value: "15306"
            - name: TOPOLOGY_FLAGS
              value: "--topo_implementation etcd2 --topo_global_server_address wesql-vtcontroller-headless:2379 --topo_global_root /vitess/global"
          ports:
            - containerPort: 15001
              name: webport
              protocol: TCP
            - containerPort: 15991
              name: grpcport
              protocol: TCP
            - containerPort: 15306
              name: serverport
              protocol: TCP
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /conf
              name: wescale-config
            - mountPath: /vtdataroot
              name: vtgate-log
      initContainers:
        - name: wait-vtctld-ready
          image: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale:0.3.0-alpha15
          imagePullPolicy: IfNotPresent
          command:
            - /scripts/wait-for-service.sh
            - vtctld
            - $(VTCTLD_HOST)
            - $(VTCTLD_GRPC_PORT)
          env:
            - name: VTCTLD_HOST
              value: wesql-vtcontroller-headless
            - name: VTCTLD_GRPC_PORT
              value: "15999"
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vtgate-log
          emptyDir: {}
        - name: scripts
          configMap:
            name: wescale-scripts
            defaultMode: 365
        - name: wescale-config
          configMap:
            name: wescale-config