apiVersion: apps/v1
kind: Deployment
metadata:
  name: wesql-vtcontroller
  namespace: default
  labels:
    app.kubernetes.io/name: wesql-vtcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wesql-vtcontroller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wesql-vtcontroller
    spec:
      containers:
        - name: etcd
          image: apecloud/apecloud-mysql-scale:0.3.0-alpha23
          imagePullPolicy: IfNotPresent
          command:
            - /scripts/etcd.sh
          lifecycle:
            postStart:
              exec:
                command:
                  - /scripts/etcd-post-start.sh
          env:
            - name: ETCD_SERVER
              value: wesql-vtcontroller-headless
            - name: ETCD_PORT
              value: "2379"
          ports:
            - containerPort: 2379
              name: etcd-client
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: etcd-client
            initialDelaySeconds: 5
            periodSeconds: 10
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data
              mountPath: /vtdataroot
        - name: vtctld
          image: apecloud/apecloud-mysql-scale:0.3.0-alpha23
          imagePullPolicy: IfNotPresent
          command:
            - /scripts/vtctld.sh
          env:
            - name: VTCTLD_GRPC_PORT
              value: "15999"
            - name: VTCTLD_WEB_PORT
              value: "15000"
            - name: TOPOLOGY_FLAGS
              value: "--topo_implementation etcd2 --topo_global_server_address wesql-vtcontroller-headless:2379 --topo_global_root /vitess/global"
          ports:
            - containerPort: 15000
              name: vtctld-webport
              protocol: TCP
            - containerPort: 15999
              name: vtctld-grpcport
              protocol: TCP
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data
              mountPath: /vtdataroot
      volumes:
        - name: scripts
          configMap:
            name: wescale-scripts
            defaultMode: 365
        - name: data
          emptyDir: {}