apiVersion: v1
kind: Service
metadata:
  name: wesql-vtcontroller-headless
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: etcd-client
    - name: vtctld-webport
      port: 15000
      protocol: TCP
      targetPort: vtctld-webport
    - name: vtctld-grpcport
      port: 15999
      protocol: TCP
      targetPort: vtctld-grpcport
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: wesql-vtcontroller
  sessionAffinity: None
  type: ClusterIP