apiVersion: v1
kind: Pod
metadata:
  name: wesql-vtcontroller
  namespace: default
  labels:
    app.kubernetes.io/name: wesql-vtcontroller
spec:
  containers:
    - command:
        - /scripts/etcd.sh
      image: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale:autoscale-demo-12
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
            command:
              - /scripts/etcd-post-start.sh
      name: etcd
      env:
        - name: ETCD_SERVER
          value: wesql-vtcontroller-headless
        - name: ETCD_PORT
          value: "2379"
        - name: CELL
          value: "zone1"
      ports:
        - containerPort: 2379
          name: etcd-client
          protocol: TCP
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "0"
          memory: "0"
        requests:
          cpu: "0"
          memory: "0"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /vtdataroot
          name: data
    - command:
        - /scripts/vtctld.sh
      image: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/apecloud-mysql-scale:autoscale-demo-12
      imagePullPolicy: IfNotPresent
      name: vtctld
      env:
        - name: CELL
          value: "zone1"
        - name: VTCTLD_GRPC_PORT
          value: "15999"
        - name: VTCTLD_WEB_PORT
          value: "15000"
        - name: TOPOLOGY_FLAGS
          value: "--topo_implementation etcd2 --topo_global_server_address wesql-vtcontroller-headless:2379 --topo_global_root /vitess/global"
      ports:
        - containerPort: 15000
          name: vtctld-webport
          protocol: TCP
        - containerPort: 15999
          name: vtctld-grpcport
          protocol: TCP
      resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
      resources:
        limits:
          cpu: "0"
          memory: "0"
        requests:
          cpu: "0"
          memory: "0"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /vtdataroot
          name: data
  volumes:
    - configMap:
        defaultMode: 365
        name: wesql-scripts
      name: scripts
    - name: data
      emptyDir: { }